import { createBundle } from '../../../src/bundles/archive.js';
import { run as makeRun, testRecord } from '../../../test/factories.js';
import type { ReaderRun } from '../../../src/historyreader.js';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import * as vscode from 'vscode';
import type { activate } from '../src/extension.js';

export async function run(): Promise<void> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try { await Promise.race([journey(), new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error('Editor journey timed out after 60 seconds.')), 60_000); })]); }
  finally { if (timer) clearTimeout(timer); }
}

async function journey(): Promise<void> {
  const extension = vscode.extensions.getExtension<Awaited<ReturnType<typeof activate>>>('logbook-local-preview.playwright-logbook-vscode');
  assert.ok(extension, 'Development extension must be discoverable');
  const logbook = await extension.activate();
  console.log('Host journey: activated');
  const roots = await logbook.getChildren();
  assert.equal(roots.length, 2, 'Multi-root grouping should appear');
  const first = roots.find((item) => item.label === 'first')!, broken = roots.find((item) => item.label === 'second')!;
  assert.ok(first); assert.ok(broken);
  const runs = await logbook.getChildren(first);
  const current = runs.find((item) => item.runId === 'current')!;
  assert.ok(current, 'Real compatible store should load');
  const brokenChildren = await logbook.getChildren(broken);
  assert.ok(brokenChildren.some((item) => item.label.includes('schema 2')), 'Incompatible second root must have its own diagnostic');
  const results = await logbook.getChildren(current);
  assert.ok(results.some((item) => item.kind === 'overview'), 'Run overview is discoverable before tests');
  assert.ok(!results.some(item => item.label.startsWith('Other results')), 'All tests appear directly under the run');
  const overviewIcon = logbook.getTreeItem(results.find(item => item.kind === 'overview')!).iconPath;
  assert.ok(overviewIcon instanceof vscode.ThemeIcon);
  assert.equal(overviewIcon.id, 'graph'); assert.equal(overviewIcon.color?.id, 'textLink.foreground');
  assert.ok(current.label.includes('00:00:00'), 'Run labels retain seconds');
  console.log('Host journey: compatible runs and isolated incompatible root loaded');
  const errorGroup = results.find((item) => item.kind === 'runErrors')!;
  assert.ok(errorGroup);
  const errors = await logbook.getChildren(errorGroup);
  const selectedError = errors.find((item) => item.label === 'Selected recorded run error')!;
  assert.ok(selectedError);
  const inspectError = logbook.getTreeItem(selectedError).command!;
  await vscode.commands.executeCommand(inspectError.command, ...(inspectError.arguments ?? []));
  const updated = new Promise<void>((resolve) => {
    const subscription = logbook.onDidChangeTreeData(() => { subscription.dispose(); resolve(); });
  });
  const recordPath = path.join(vscode.workspace.workspaceFolders![0]!.uri.fsPath, '.logbook/runs/current.json');
  const record = JSON.parse(await fs.readFile(recordPath, 'utf8')) as { globalErrors: { message: string; stack: null; snippet: null; location: null }[] };
  record.globalErrors.unshift({ message: 'Inserted recorded run error', stack: null, snippet: null, location: null });
  await fs.writeFile(recordPath, JSON.stringify(record));
  await updated;
  await vscode.commands.executeCommand('logbook.refresh');
  const refreshedErrors = await logbook.getChildren(errorGroup);
  assert.equal(refreshedErrors.find((item) => item.label === selectedError.label)?.id, selectedError.id, 'Run error identity should survive index movement on refresh');
  console.log('Host journey: watcher refresh and stable recorded run errors verified');
  const failure = results.find((item) => item.kind === 'result' && item.description?.startsWith('Failed ·'))!;
  assert.ok(failure);
  const statusIcon = logbook.getTreeItem(failure).iconPath;
  assert.ok(statusIcon instanceof vscode.ThemeIcon);
  assert.equal(statusIcon.id, 'error'); assert.equal(statusIcon.color?.id, 'testing.iconFailed');
  const command = logbook.getTreeItem(failure).command!;
  await vscode.commands.executeCommand(command.command, ...(command.arguments ?? []));
  console.log('Host journey: result and history opened');
  await vscode.commands.executeCommand('logbook.compareHistory', 1);
  assert.ok(vscode.window.tabGroups.all.flatMap((group) => group.tabs).some((tab) => tab.label === 'Logbook execution comparison'), 'Comparison opens a separate pinned panel');
  await vscode.commands.executeCommand('logbook.inspectHistory', 1);
  await vscode.commands.executeCommand('logbook.refresh');
  await vscode.commands.executeCommand('logbook.returnToComparedResult');
  console.log('Host journey: pinned comparison survives selection changes and refresh');
  await vscode.commands.executeCommand('logbook.openSource');
  console.log('Host journey: current source opened');
  let editor = vscode.window.activeTextEditor;
  assert.ok(editor); assert.equal(editor.selection.start.line, 2, 'Current execution opens its recorded third line');
  assert.ok(editor.document.uri.path.endsWith('/tests/ui.spec.ts'));
  await vscode.commands.executeCommand('logbook.openFailure');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 0, 'Failure location uses structured error location, separately from test definition');
  console.log('Host journey: distinct definition and failure locations verified');
  assert.ok(vscode.window.tabGroups.all.flatMap((group) => group.tabs).some((tab) => tab.input instanceof vscode.TabInputWebview), 'Opening source must preserve the adjacent history panel');
  // History contains current/main and previous/main, excluding the feature run by default.
  await vscode.commands.executeCommand('logbook.inspectHistory', 1);
  console.log('Host journey: older history selected');
  await vscode.commands.executeCommand('logbook.openSource');
  editor = vscode.window.activeTextEditor;
  console.log('Host journey: historical source opened');
  assert.ok(editor); assert.equal(editor.selection.start.line, 1, 'Earlier history execution opens its own recorded second line');
  await vscode.commands.executeCommand('logbook.refresh');
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 1, 'Refresh must preserve the selected older execution');
  await vscode.commands.executeCommand('logbook.inspectHistory', -1);
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 1, 'Invalid history messages must not change selection');
  console.log('Host journey: source navigation and refresh verified');
  const mappedRoot = vscode.workspace.workspaceFolders![0]!.uri.fsPath;
  const gitState = () => execFileSync('git', ['-C', mappedRoot, 'status', '--porcelain'], { encoding: 'utf8' });
  const head = () => execFileSync('git', ['-C', mappedRoot, 'rev-parse', 'HEAD'], { encoding: 'utf8' });
  const beforeStatus = gitState(), beforeHead = head();
  await vscode.commands.executeCommand('logbook.viewComparedSource', 'baseline');
  assert.equal(vscode.window.activeTextEditor?.document.uri.scheme, 'logbook-history');
  assert.ok(vscode.window.activeTextEditor?.document.getText().startsWith('// mapped source'));
  await vscode.commands.executeCommand('logbook.diffComparedSource');
  const diff = vscode.window.tabGroups.all.flatMap((group) => group.tabs).find((tab) => tab.input instanceof vscode.TabInputTextDiff && tab.input.original.scheme === 'logbook-history');
  assert.ok(diff && diff.input instanceof vscode.TabInputTextDiff);
  assert.notEqual(diff.input.original.path, diff.input.modified.path, 'Two recorded commits must remain distinct virtual resources');
  assert.equal(head(), beforeHead); assert.equal(gitState(), beforeStatus);
  console.log('Host journey: read-only committed source and native diff preserve HEAD and working tree');
  const localRecord = JSON.parse(await fs.readFile(recordPath, 'utf8')) as ReaderRun;
  const localFailure = localRecord.tests.find(test => test.outcome === 'unexpected')!;
  const ci = makeRun('ci-imported', '2026-01-04T00:00:00.000Z');
  ci.status = 'failed'; ci.summary = { total: 1, passed: 0, failed: 1, flaky: 0, skipped: 0 };
  ci.tests = [{ ...testRecord(localFailure.testId, 'unexpected'), project: localFailure.project, file: localFailure.file!, title: localFailure.title, line: 3, repeatEachIndex: localFailure.repeatEachIndex ?? 0, firstError: localFailure.firstError }];
  const zip = path.join(mappedRoot, 'ci.logbook.zip'), invalidZip = path.join(mappedRoot, 'bad.zip');
  await fs.writeFile(zip, await createBundle([ci], 'editor-project')); await fs.writeFile(invalidZip, 'not zip');
  const beforeRuns = await logbook.getChildren(first);
  const preparation = await logbook.prepareBundleImport(first.folderKey, [zip, invalidZip], 'editor-project');
  assert.deepEqual(preparation.preview.added, ['ci-imported']); assert.equal(preparation.rejected.length, 1);
  assert.equal((await logbook.getChildren(first)).length, beforeRuns.length, 'Review must not mutate history');
  const aborted = new AbortController(); aborted.abort();
  await assert.rejects(logbook.commitBundleImport(preparation, aborted.signal));
  assert.ok(!(await logbook.getChildren(first)).some(item => item.runId === 'ci-imported'), 'Cancelled commit must leave target unchanged');
  assert.deepEqual((await logbook.commitBundleImport(preparation)).added, ['ci-imported']);
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 1, 'Import refresh preserves selected historical execution');
  const duplicate = await logbook.prepareBundleImport(first.folderKey, [zip], 'editor-project');
  assert.deepEqual((await logbook.commitBundleImport(duplicate)).skipped, ['ci-imported']);
  await fs.writeFile(zip, await createBundle([{ ...ci, title: 'conflict' }], 'editor-project'));
  const conflict = await logbook.prepareBundleImport(first.folderKey, [zip], 'editor-project');
  assert.deepEqual((await logbook.commitBundleImport(conflict)).conflicts, ['ci-imported']);
  await assert.rejects(logbook.prepareBundleImport(first.folderKey, [zip], 'wrong-project'));
  assert.ok((await logbook.getChildren(broken)).some(item => item.label.includes('schema 2')), 'Import never modifies the other workspace store');
  const importedNode = (await logbook.getChildren(first)).find(item => item.runId === 'ci-imported')!;
  const importedResult = (await logbook.getChildren(importedNode)).find(item => item.kind === 'result')!;
  await vscode.commands.executeCommand('logbook.inspect', importedResult.id);
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 2, 'Imported CI failure navigates the mapped local source');
  await vscode.commands.executeCommand('logbook.inspectHistory', 1);
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 2, 'Matching current local execution appears beside imported CI failure');
  await vscode.commands.executeCommand('logbook.inspectHistory', 2);
  await vscode.commands.executeCommand('logbook.openSource');
  assert.equal(vscode.window.activeTextEditor?.selection.start.line, 1, 'Matching older local execution also appears in blended history');
  console.log('Host journey: reviewed import, cancellation, duplicates, conflicts, multi-root isolation and CI → local history → source passed');
  const watchersBeforeRemoval = roots.length;
  assert.equal(watchersBeforeRemoval, 2);
  assert.equal(vscode.workspace.updateWorkspaceFolders(1, 1), true);
  await new Promise<void>((resolve) => {
    const subscription = vscode.workspace.onDidChangeWorkspaceFolders(() => { subscription.dispose(); resolve(); });
  });
  console.log('Host journey: root removal event received');
  // setup is asynchronous; wait on tree updates rather than a guessed delay.
  if ((await logbook.getChildren()).some((item) => item.kind === 'folder')) await new Promise<void>((resolve) => {
    const subscription = logbook.onDidChangeTreeData(() => { subscription.dispose(); resolve(); });
  });
  assert.ok((await logbook.getChildren()).some((item) => item.runId === 'current'), 'One remaining folder should show runs directly');
  console.log('VS Code host: failure → scoped history → source, refresh, invalid actions and multi-root isolation passed.');
}
