export const REPORT_CSS = `
:root{font-family:system-ui,-apple-system,sans-serif;color-scheme:light dark;--bg:#f8fafc;--fg:#142233;--card:#fff;--border:#d7e0e8;--muted:#5d6b7b;--accent:#175cd3}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg)}main{max-width:1200px;margin:auto;padding:1.5rem}header{padding:1.5rem 0}h1{margin:.2rem 0;font-size:1.8rem}h2{font-size:1.25rem}small,.muted{color:var(--muted)}.badge{display:inline-block;border-radius:99px;padding:.2rem .65rem;background:#ddeaff;color:#143e87;font-weight:700}.banner{padding:.8rem;background:#fff0cc;border:1px solid #bd7a00;border-radius:.5rem;margin:.6rem 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:.75rem;margin:1rem 0}.card{background:var(--card);border:1px solid var(--border);border-radius:.7rem;padding:1rem}.card strong{display:block;font-size:1.6rem;margin-top:.3rem}.tabs{display:flex;gap:.25rem;overflow-x:auto;border-bottom:1px solid var(--border);margin:1.5rem 0 1rem}.tabs button{background:none;border:0;border-bottom:3px solid transparent;color:var(--fg);font:inherit;padding:.7rem 1rem;cursor:pointer;white-space:nowrap}.tabs button[aria-selected=true]{border-color:var(--accent);font-weight:700}.panel[hidden]{display:none}.filters{display:flex;flex-wrap:wrap;gap:.5rem;margin:1rem 0}.filters input,.filters select{padding:.5rem;border:1px solid var(--border);border-radius:.4rem;background:var(--card);color:var(--fg)}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;background:var(--card)}th,td{text-align:left;border-bottom:1px solid var(--border);padding:.65rem;vertical-align:top}th button{font:inherit;background:none;border:0;color:inherit;cursor:pointer;font-weight:700}tr[data-expand]{cursor:pointer}tr[data-expand]:focus{outline:2px solid var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.details{padding:1rem;background:var(--bg);border-radius:.4rem}.status{font-weight:700}.status.unexpected{color:#b42318}.status.flaky{color:#a15c00}.status.expected{color:#0a7a48}footer{color:var(--muted);padding:2rem 0}
svg{width:100%;max-width:850px;height:180px;background:var(--card);border:1px solid var(--border);border-radius:.5rem;margin:.5rem 0}svg text{fill:var(--fg);font-size:11px}.table-wrap small{display:block;margin-top:.2rem}a{color:var(--accent)}
@media(prefers-color-scheme:dark){:root{--bg:#111a24;--fg:#e6edf5;--card:#1a2836;--border:#344557;--muted:#a0afbf;--accent:#77a9ff}.badge{background:#21466e;color:#d9ecff}.banner{background:#493b18;color:#ffdf8a}}
`;

export const REPORT_JS = `
const model=JSON.parse(document.getElementById('lb-data').textContent);
const links=JSON.parse(document.getElementById('lb-links').textContent);
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);if(cls)el.className=cls;return el};
const add=(parent,...children)=>{for(const child of children)parent.appendChild(child);return parent};
const clear=(element)=>{while(element.firstChild)element.removeChild(element.firstChild)};
const duration=(ms)=>ms<1000?Math.round(ms)+'ms':ms<60000?(ms/1000).toFixed(1)+'s':Math.floor(ms/60000)+'m '+Math.floor(ms%60000/1000)+'s';
const tabs=[...document.querySelectorAll('[data-tab]')];
function selectTab(name){for(const tab of tabs){const active=tab.dataset.tab===name;tab.setAttribute('aria-selected',String(active));document.getElementById('tab-'+tab.dataset.tab).hidden=!active}}
for(const tab of tabs){tab.addEventListener('click',()=>selectTab(tab.dataset.tab));tab.addEventListener('keydown',(event)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const step=event.key==='ArrowRight'?1:-1;const next=tabs[(tabs.indexOf(tab)+step+tabs.length)%tabs.length];next.focus();selectTab(next.dataset.tab)}})}
selectTab('tests');
const tests=model.run.tests;
const search=document.getElementById('lb-search'),status=document.getElementById('lb-status'),project=document.getElementById('lb-project'),tag=document.getElementById('lb-tag');
for(const value of [...new Set(tests.map(test=>test.project))].sort()){const option=node('option',value);option.value=value;project.appendChild(option)}
for(const value of [...new Set(tests.flatMap(test=>test.tags))].sort()){const option=node('option',value);option.value=value;tag.appendChild(option)}
let sortKey='title',descending=false;
function detailRow(test){const row=node('tr'),cell=node('td');cell.colSpan=6;const box=node('div',undefined,'details');for(const attempt of test.attempts){add(box,node('p','Attempt '+(attempt.retry+1)+' · '+attempt.status+' · '+duration(attempt.durationMs)));for(const error of attempt.errors)add(box,node('pre',error.message+(error.stack?String.fromCharCode(10)+error.stack:'')));for(const attachment of attempt.attachments){const link=node('a',attachment.name);const href=attachment.path&&links[attachment.path];if(href){link.href=href;link.rel='noopener noreferrer'}else{link.removeAttribute('href')}add(box,link,node('span',' '))}}if(!test.attempts.length)add(box,node('p','No attempt details stored.'));add(cell,box);add(row,cell);return row}
function renderTests(){const body=document.getElementById('lb-tests-body');clear(body);const q=search.value.toLowerCase();const matches=tests.filter(test=>(!q||(test.title+' '+test.file+' '+test.tags.join(' ')).toLowerCase().includes(q))&&(!status.value||test.outcome===status.value)&&(!project.value||test.project===project.value)&&(!tag.value||test.tags.includes(tag.value)));matches.sort((a,b)=>{const left=sortKey==='duration'?a.durationMs:a.title,right=sortKey==='duration'?b.durationMs:b.title;const diff=left<right?-1:left>right?1:0;return descending?-diff:diff});for(const test of matches){const row=node('tr');row.tabIndex=0;row.dataset.expand='true';const name=node('td');add(name,node('strong',test.title),node('small',test.file+':'+test.line));add(row,node('td',test.outcome,'status '+test.outcome),name,node('td',test.project),node('td',test.tags.join(', ')),node('td',duration(test.durationMs)),node('td',test.attemptCount));const detail=detailRow(test);detail.hidden=true;const toggle=()=>{detail.hidden=!detail.hidden};row.addEventListener('click',toggle);row.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}});add(body,row,detail)}if(!matches.length){const row=node('tr'),cell=node('td','No tests match these filters.');cell.colSpan=6;add(row,cell);add(body,row)}}
for(const control of [search,status,project,tag])control.addEventListener('input',renderTests);
for(const button of document.querySelectorAll('[data-sort]'))button.addEventListener('click',()=>{const next=button.dataset.sort;descending=sortKey===next?!descending:false;sortKey=next;renderTests()});
renderTests();
`;

export const REPORT_EXTRA_JS = `
function table(parent,headings,rows){const wrap=node("div",undefined,"table-wrap"),grid=node("table"),head=node("thead"),headRow=node("tr"),body=node("tbody");for(const name of headings)add(headRow,node("th",name));add(head,headRow);for(const values of rows){const row=node("tr");for(const value of values)add(row,node("td",value===null||value===undefined?"":value));add(body,row)}add(grid,head,body);add(wrap,grid);add(parent,wrap)}
function externalLink(label,url){if(typeof url!=="string"||!/^https?:/i.test(url))return node("span",label);const link=node("a",label);link.href=url;link.rel="noopener noreferrer";return link}
function renderFailures(){const panel=document.getElementById("tab-failures");add(panel,node("h2","Failures"));const groups=new Map();for(const test of tests.filter(item=>item.outcome==="unexpected"||item.outcome==="flaky")){const first=test.firstError?.message?.split(String.fromCharCode(10))[0]||"No error message";const group=groups.get(first)||[];group.push(test);groups.set(first,group)}if(!groups.size)add(panel,node("p","No failures or flaky tests in this run."));for(const [message,items] of groups){add(panel,node("h3",message+" ("+items.length+")"));const list=node("ul");for(const item of items)add(list,node("li",item.title+" · "+item.file+" ["+item.project+"]"));add(panel,list)}if(model.comparison){for(const [key,label] of [["newFailures","New failures"],["fixed","Fixed"],["stillFailing","Still failing"]]){const items=model.comparison[key];add(panel,node("h3",label+" ("+items.length+")"));const list=node("ul");for(const item of items)add(list,node("li",item.title+" · "+item.file+" ["+item.project+"]"));add(panel,list)}}}
const svgNS="http"+"://www.w3.org/2000/svg";
function svgNode(name,attributes){const element=document.createElementNS(svgNS,name);for(const [key,value] of Object.entries(attributes))element.setAttribute(key,String(value));return element}
function renderTrends(){const panel=document.getElementById("tab-trends");add(panel,node("h2","Trends"));const history=model.history;if(!history.length){add(panel,node("p","No run history available."));return}const chart=svgNode("svg",{viewBox:"0 0 850 180",role:"img","aria-label":"Pass rate and duration over runs"});const maxDuration=Math.max(1,...history.map(item=>item.durationMs));const points=[];history.forEach((item,index)=>{const x=30+(790*(index+.5)/history.length),rate=item.summary.total?item.summary.passed/item.summary.total:0,y=150-110*rate;const bar=svgNode("rect",{x:x-12,y:150-90*item.durationMs/maxDuration,width:24,height:90*item.durationMs/maxDuration,fill:"#8badd8",opacity:.6});const barTip=svgNode("title",{});barTip.textContent=item.runId+" · "+item.startedAt+" · "+item.status;add(bar,barTip);add(chart,bar);const dot=svgNode("circle",{cx:x,cy:y,r:4,fill:"#175cd3"});const tip=svgNode("title",{});tip.textContent=item.runId+" · "+item.startedAt+" · "+item.status;add(dot,tip);add(chart,dot);const label=svgNode("text",{x:x-20,y:170});label.textContent=item.status;add(chart,label);points.push(x+","+y)});const line=svgNode("polyline",{points:points.join(" "),fill:"none",stroke:"#175cd3","stroke-width":2});chart.insertBefore(line,chart.firstChild);add(panel,chart);table(panel,["Run","Date","Status","Pass rate","Duration"],history.map(item=>[item.runId,item.startedAt,item.status,item.summary.total?Math.round(100*item.summary.passed/item.summary.total)+"%":"0%",duration(item.durationMs)]))}
function renderFlaky(){const panel=document.getElementById("tab-flaky");add(panel,node("h2","Flaky tests"));if(!model.flaky.length){add(panel,node("p","No flaky tests detected in the last "+model.history.length+" runs."));return}table(panel,["Test","File","Project","Score","Runs","Flaky runs","Fails"],model.flaky.map(item=>[item.title,item.file,item.project,item.score.toFixed(2),item.runs,item.flakyRuns,item.fails]))}
function renderRun(){const panel=document.getElementById("tab-run"),run=model.run,env=run.env;add(panel,node("h2","Run details"));const rows=[["Run ID",run.runId],["Title",run.title],["Start",run.startedAt],["End",run.endedAt],["Duration",duration(run.durationMs)],["Expected shards",run.expectedShards],["Received shards",run.receivedShards.join(", ")],["CI provider",env.ci?.provider],["Build ID",env.ci?.buildId],["Branch",env.git.branch],["Commit",env.git.commit],["PR",env.git.prNumber],["Repository",env.git.repository],["Playwright",env.playwrightVersion],["Node",env.machine.node],["OS",env.machine.os],["Architecture",env.machine.arch],["CPUs",env.machine.cpus],["Workers",env.workers]];table(panel,["Field","Value"],rows);if(env.ci?.buildUrl)add(panel,externalLink("Open CI build",env.ci.buildUrl))}
function renderProject(){const panel=document.getElementById("tab-project"),info=model.run.project;add(panel,node("h2","Project"));table(panel,["Field","Value"],[["Name",info.name],["Config file",info.configFile],["Workers",info.workers]]);add(panel,node("h3","Playwright projects"));table(panel,["Name","Test directory"],info.projects.map(item=>[item.name,item.testDir]));add(panel,node("h3","Files"));table(panel,["File","Total","Failed","Flaky","Skipped","Duration"],model.files.map(item=>[item.file,item.total,item.failed,item.flaky,item.skipped,duration(item.durationMs)]));add(panel,node("h3","Tags"));table(panel,["Tag","Count"],model.tags.map(item=>[item.tag,item.count]));add(panel,node("h3","Slowest tests"));table(panel,["Test","File","Project","Duration"],model.slowest.map(item=>[item.title,item.file,item.project,duration(item.durationMs)]))}
renderFailures();renderTrends();renderFlaky();renderRun();renderProject();
`;
