export const REPORT_CSS = `
:root{font-family:system-ui,-apple-system,sans-serif;color-scheme:light dark;--bg:#f8fafc;--fg:#142233;--card:#fff;--border:#d7e0e8;--muted:#5d6b7b;--accent:#175cd3}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg)}main{max-width:1200px;margin:auto;padding:1.5rem}header{padding:1.5rem 0}h1{margin:.2rem 0;font-size:1.8rem}h2{font-size:1.25rem}small,.muted{color:var(--muted)}.badge{display:inline-block;border-radius:99px;padding:.2rem .65rem;background:#ddeaff;color:#143e87;font-weight:700}.banner{padding:.8rem;background:#fff0cc;border:1px solid #bd7a00;border-radius:.5rem;margin:.6rem 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:.75rem;margin:1rem 0}.card{background:var(--card);border:1px solid var(--border);border-radius:.7rem;padding:1rem}.card strong{display:block;font-size:1.6rem;margin-top:.3rem}.tabs{display:flex;gap:.25rem;overflow-x:auto;border-bottom:1px solid var(--border);margin:1.5rem 0 1rem}.tabs button{background:none;border:0;border-bottom:3px solid transparent;color:var(--fg);font:inherit;padding:.7rem 1rem;cursor:pointer;white-space:nowrap}.tabs button[aria-selected=true]{border-color:var(--accent);font-weight:700}.panel[hidden]{display:none}.filters{display:flex;flex-wrap:wrap;gap:.5rem;margin:1rem 0}.filters input,.filters select{padding:.5rem;border:1px solid var(--border);border-radius:.4rem;background:var(--card);color:var(--fg)}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;background:var(--card)}th,td{text-align:left;border-bottom:1px solid var(--border);padding:.65rem;vertical-align:top}th button{font:inherit;background:none;border:0;color:inherit;cursor:pointer;font-weight:700}tr[data-expand]{cursor:pointer}tr[data-expand]:focus{outline:2px solid var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.details{padding:1rem;background:var(--bg);border-radius:.4rem}.status{font-weight:700}.status.unexpected{color:#b42318}.status.flaky{color:#a15c00}.status.expected{color:#0a7a48}footer{color:var(--muted);padding:2rem 0}
@media(prefers-color-scheme:dark){:root{--bg:#111a24;--fg:#e6edf5;--card:#1a2836;--border:#344557;--muted:#a0afbf;--accent:#77a9ff}.badge{background:#21466e;color:#d9ecff}.banner{background:#493b18;color:#ffdf8a}}
`;

export const REPORT_JS = `
const model=JSON.parse(document.getElementById('lb-data').textContent);
const links=JSON.parse(document.getElementById('lb-links').textContent);
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);if(cls)el.className=cls;return el};
const add=(parent,...children)=>{for(const child of children)parent.appendChild(child);return parent};
const clear=(element)=>{while(element.firstChild)element.removeChild(element.firstChild)};
const duration=(ms)=>ms<1000?Math.round(ms)+'ms':ms<60000?(ms/1000).toFixed(1)+'s':Math.floor(ms/60000)+'m '+Math.floor(ms%60000/1000)+'s';
const tabs=[...document.querySelectorAll('[data-tab]')];
function selectTab(name){for(const tab of tabs){const active=tab.dataset.tab===name;tab.setAttribute('aria-selected',String(active));document.getElementById('tab-'+tab.dataset.tab).hidden=!active}}
for(const tab of tabs){tab.addEventListener('click',()=>selectTab(tab.dataset.tab));tab.addEventListener('keydown',(event)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const step=event.key==='ArrowRight'?1:-1;const next=tabs[(tabs.indexOf(tab)+step+tabs.length)%tabs.length];next.focus();selectTab(next.dataset.tab)}})}
selectTab('tests');
const tests=model.run.tests;
const search=document.getElementById('lb-search'),status=document.getElementById('lb-status'),project=document.getElementById('lb-project'),tag=document.getElementById('lb-tag');
for(const value of [...new Set(tests.map(test=>test.project))].sort()){const option=node('option',value);option.value=value;project.appendChild(option)}
for(const value of [...new Set(tests.flatMap(test=>test.tags))].sort()){const option=node('option',value);option.value=value;tag.appendChild(option)}
let sortKey='title',descending=false;
function detailRow(test){const row=node('tr'),cell=node('td');cell.colSpan=6;const box=node('div',undefined,'details');for(const attempt of test.attempts){add(box,node('p','Attempt '+(attempt.retry+1)+' · '+attempt.status+' · '+duration(attempt.durationMs)));for(const error of attempt.errors)add(box,node('pre',error.message+(error.stack?'\n'+error.stack:'')));for(const attachment of attempt.attachments){const link=node('a',attachment.name);const href=attachment.path&&links[attachment.path];if(href){link.href=href;link.rel='noopener noreferrer'}else{link.removeAttribute('href')}add(box,link,node('span',' '))}}if(!test.attempts.length)add(box,node('p','No attempt details stored.'));add(cell,box);add(row,cell);return row}
function renderTests(){const body=document.getElementById('lb-tests-body');clear(body);const q=search.value.toLowerCase();const matches=tests.filter(test=>(!q||(test.title+' '+test.file+' '+test.tags.join(' ')).toLowerCase().includes(q))&&(!status.value||test.outcome===status.value)&&(!project.value||test.project===project.value)&&(!tag.value||test.tags.includes(tag.value)));matches.sort((a,b)=>{const left=sortKey==='duration'?a.durationMs:a.title,right=sortKey==='duration'?b.durationMs:b.title;const diff=left<right?-1:left>right?1:0;return descending?-diff:diff});for(const test of matches){const row=node('tr');row.tabIndex=0;row.dataset.expand='true';const name=node('td');add(name,node('strong',test.title),node('small',test.file+':'+test.line));add(row,node('td',test.outcome,'status '+test.outcome),name,node('td',test.project),node('td',test.tags.join(', ')),node('td',duration(test.durationMs)),node('td',test.attemptCount));const detail=detailRow(test);detail.hidden=true;const toggle=()=>{detail.hidden=!detail.hidden};row.addEventListener('click',toggle);row.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}});add(body,row,detail)}if(!matches.length){const row=node('tr'),cell=node('td','No tests match these filters.');cell.colSpan=6;add(row,cell);add(body,row)}}
for(const control of [search,status,project,tag])control.addEventListener('input',renderTests);
for(const button of document.querySelectorAll('[data-sort]'))button.addEventListener('click',()=>{const next=button.dataset.sort;descending=sortKey===next?!descending:false;sortKey=next;renderTests()});
renderTests();
`;
