import { buildStyles } from './template.js';
import { formatDuration } from './model.js';
import type { ReportModel } from './model.js';
import type { TestRecord } from './schema.js';

const escape = (value: unknown): string => String(value ?? 'Unknown').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

/** Static, offline snapshot of one recorded execution and its available history. */
export function renderTestReport(model: ReportModel, test: TestRecord, links: Record<string, string>): string {
  const history = [...(model.testHistory[test.testId] ?? [])].reverse();
  const baseline = history[0];
  const attempts = test.attempts.map((attempt, index) => `<section class="section-card"><h3>Attempt ${index + 1} · ${escape(attempt.status)}</h3><p>${formatDuration(attempt.durationMs)}</p>${attempt.errors.map(error => `<div><pre>${escape(error.message)}</pre>${error.snippet ? `<pre>${escape(error.snippet)}</pre>` : ''}${error.stack ? `<details><summary>Stack trace</summary><pre>${escape(error.stack)}</pre></details>` : ''}</div>`).join('')}${attempt.attachments.map(attachment => `<p>${escape(attachment.name)} · ${attachment.path && links[attachment.path] ? `<a href="${escape(links[attachment.path])}">Open retained file</a>` : attachment.dataUri ? 'Inline attachment' : 'File not retained in this export'}</p>${attachment.dataUri && /^data:image\/(?:png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(attachment.dataUri) ? `<img src="${attachment.dataUri}" alt="${escape(attachment.name)}" style="max-width:100%;max-height:300px">` : ''}`).join('')}${attempt.steps?.length ? `<h4>Steps</h4><ol>${attempt.steps.map(step => `<li>${escape(step.title)} · ${formatDuration(step.durationMs)}${step.failed ? ' · failed' : ''}</li>`).join('')}</ol>` : ''}${attempt.stdout ? `<details><summary>stdout</summary><pre>${escape(attempt.stdout)}</pre></details>` : ''}${attempt.stderr ? `<details><summary>stderr</summary><pre>${escape(attempt.stderr)}</pre></details>` : ''}</section>`).join('');
  const rows = history.map(entry => `<tr><td>${escape(entry.startedAt)}</td><td>${escape(entry.runId)}</td><td>${escape(entry.branch)}</td><td>${escape(entry.status)}</td><td>${formatDuration(entry.durationMs)}</td><td>${entry.complete ? 'Complete' : 'Incomplete'}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(test.title)} · Logbook</title><style>${buildStyles()}</style></head><body><main class="container"><p class="eyebrow">Logbook / test export</p><h1>${escape(test.title)}</h1><p>${escape(test.file)}:${escape(test.line)} · ${escape(test.project)} · Repeat ${escape(test.repeatEachIndex)}</p><p>Run <code>${escape(model.run.runId)}</code> · ${escape(model.run.startedAt)} · ${model.run.complete ? 'Complete' : 'Incomplete'} · ${escape(test.status)} · ${formatDuration(test.durationMs)}</p><p>Expected: ${escape(test.expectedStatus)} · Outcome: ${escape(test.outcome)}${test.tags.length ? ` · Tags: ${escape(test.tags.join(', '))}` : ''}${test.caseIds.length ? ` · Case IDs: ${escape(test.caseIds.join(', '))}` : ''}</p>${test.annotations.length ? `<p>Annotations: ${escape(test.annotations.map(item => `${item.type}${item.description ? `: ${item.description}` : ''}`).join(' · '))}</p>` : ''}<p class="muted">Recorded evidence is a snapshot. Missing runs and incomplete records do not establish a pass.</p><section><h2>Selected execution</h2>${test.firstError ? `<pre>${escape(test.firstError.message)}</pre>` : '<p>No first error recorded.</p>'}${attempts || '<p>Attempt details unavailable.</p>'}</section><section><h2>History · ${history.length}</h2>${history.length ? `<div class="table-wrap"><table><thead><tr><th>Recorded</th><th>Run</th><th>Branch</th><th>Status</th><th>Duration</th><th>Run state</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<p>No earlier matching execution is available.</p>'}</section>${baseline ? `<section><h2>Compared with ${escape(baseline.runId)}</h2><div class="test-comparison">${[['Status', baseline.status, test.status], ['Attempts', baseline.attemptCount, test.attemptCount], ['Duration', formatDuration(baseline.durationMs), formatDuration(test.durationMs)], ['Recorded error', baseline.firstError ?? 'No recorded error', test.firstError?.message.split(/\r?\n/)[0] ?? 'No recorded error']].map(([label, before, after]) => `<div><strong>${escape(label)}</strong><span>${escape(before)}</span><span>→</span><span>${escape(after)}</span></div>`).join('')}</div><p class="muted">Recorded values only; similar errors and timing changes do not establish a cause.</p></section>` : ''}</main></body></html>`;
}
